### ISSUE TITLE
Getting result even if stopforumspam returns false

### ISSUE THREAD

**Issue by codecowboy** [deltreey/stopforumspam#2]
Is there a method for verifying that the call to the stopforumspam api was successful?

**Comment by deltreey** [comment]
the promises use a standard syntax of `.then` for successes and `.catch` for unsuccessful ones.

```javascript
// do stuff
.then(function (result) {
    // success! do stuff with result
})
.catch(function (error) {
    // deal with the error that occurred
});
```

**Comment by deltreey** [comment]
It seems I was mistaken.  It's `.fail` not `.catch` in this version of q.  I will update the docs.

```javascript
return foo()
.then(function (value) {
    throw new Error("Can't bar.");
})
.fail(function (error) {
    // We get here with either foo's error or bar's error
});
```

for more details, see the q library

https://github.com/kriskowal/q#tutorial
https://github.com/kriskowal/q#handling-errors

**Comment by deltreey** [comment]
alternatively, you could try the (untested) sync functions.

from the readme:
```javascript
var spammer = stopforumspam.isSpammerSync({ ip: '123.456.789.100', email: 'test@test.com', username: 'Spammer!' });
if (spammer) {
    // do stuff
}
// User functions too!
var sfsUser = stopforumspam.User('127.0.0.1', 'test@test.com', 'testUserName');
if (sfsUser.isSpammerSync()) {
    // do stuff
}
```

**Comment by deltreey** [comment]
if your question was answered, please close this issue.  If not, I'm happy to help with any further confusion.
